import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-ambulance-payer-denial-recovery",
  "engine": "recovery",
  "title": "Ambulance Payer Denial Recovery",
  "shortTitle": "Ambulance Payer Denial Recovery",
  "tagline": "Quantify, recover, and prevent financial leakage through ambulance payer denial recovery",
  "industry": "Ambulance Revenue Integrity",
  "uiPort": 4604,
  "apiPort": 5604,
  "accent": "#7e22ce",
  "currency": "USD",
  "primaryOutcome": "Ambulance Payer Denial Recovery converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect dispatches, trips, patient eligibility, origin and destination, loaded mileage, service level, medical necessity, certifications, signatures, claims, denials, and remittances in one accountable recovery workflow.",
  "calculation": {
    "actualKey": "paidAmount",
    "expectedKey": "expectedAmount",
    "actualLabel": "Payer Paid Amount",
    "expectedLabel": "Supported Transport Reimbursement",
    "varianceLabel": "Unrecovered supported value",
    "direction": "expected-minus-actual",
    "finding": "Ambulance Payer Denial Recovery evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective governing agreement and applicable rules",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare and submit the recovery or correction package",
      "Track counterparty response and reconcile realized outcome"
    ]
  }
},[
feature("dispatch-trip-ingestion","APD01","Dispatch trip ingestion","Execute dispatch trip ingestion using dispatches, trips, patient eligibility, origin and destination, loaded mileage, service level, medical necessity, certifications, signatures, claims, denials, and remittances.","Produce a governed dispatch trip ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Provider / Transport","text","Provider / Transport · Standard Case"],["caseReference","Dispatch trip ingestion Reference","text","APD01-2026-001"],["paidAmount","Payer Paid Amount","currency",660500],["expectedAmount","Supported Transport Reimbursement","currency",779390],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Dispatch trip ingestion case","Patient payer eligibility case","Origin destination modifiers case","Loaded mileage calculation case","Service level determination case"]}),
feature("patient-payer-eligibility","APD02","Patient payer eligibility","Execute patient payer eligibility using dispatches, trips, patient eligibility, origin and destination, loaded mileage, service level, medical necessity, certifications, signatures, claims, denials, and remittances.","Produce a governed patient payer eligibility decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Provider / Transport","text","Provider / Transport · Standard Case"],["caseReference","Patient payer eligibility Reference","text","APD02-2026-001"],["paidAmount","Payer Paid Amount","currency",660500],["expectedAmount","Supported Transport Reimbursement","currency",779390],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Dispatch trip ingestion case","Patient payer eligibility case","Origin destination modifiers case","Loaded mileage calculation case","Service level determination case"]}),
feature("origin-destination-modifiers","APD03","Origin destination modifiers","Execute origin destination modifiers using dispatches, trips, patient eligibility, origin and destination, loaded mileage, service level, medical necessity, certifications, signatures, claims, denials, and remittances.","Produce a governed origin destination modifiers decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Provider / Transport","text","Provider / Transport · Standard Case"],["caseReference","Origin destination modifiers Reference","text","APD03-2026-001"],["paidAmount","Payer Paid Amount","currency",660500],["expectedAmount","Supported Transport Reimbursement","currency",779390],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Dispatch trip ingestion case","Patient payer eligibility case","Origin destination modifiers case","Loaded mileage calculation case","Service level determination case"]}),
feature("loaded-mileage-calculation","APD04","Loaded mileage calculation","Execute loaded mileage calculation using dispatches, trips, patient eligibility, origin and destination, loaded mileage, service level, medical necessity, certifications, signatures, claims, denials, and remittances.","Produce a governed loaded mileage calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Provider / Transport","text","Provider / Transport · Standard Case"],["caseReference","Loaded mileage calculation Reference","text","APD04-2026-001"],["paidAmount","Payer Paid Amount","currency",660500],["expectedAmount","Supported Transport Reimbursement","currency",779390],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Dispatch trip ingestion case","Patient payer eligibility case","Origin destination modifiers case","Loaded mileage calculation case","Service level determination case"]}),
feature("service-level-determination","APD05","Service level determination","Execute service level determination using dispatches, trips, patient eligibility, origin and destination, loaded mileage, service level, medical necessity, certifications, signatures, claims, denials, and remittances.","Produce a governed service level determination decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Provider / Transport","text","Provider / Transport · Standard Case"],["caseReference","Service level determination Reference","text","APD05-2026-001"],["paidAmount","Payer Paid Amount","currency",660500],["expectedAmount","Supported Transport Reimbursement","currency",779390],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Dispatch trip ingestion case","Patient payer eligibility case","Origin destination modifiers case","Loaded mileage calculation case","Service level determination case"]}),
feature("medical-necessity-evidence","APD06","Medical necessity evidence","Execute medical necessity evidence using dispatches, trips, patient eligibility, origin and destination, loaded mileage, service level, medical necessity, certifications, signatures, claims, denials, and remittances.","Produce a governed medical necessity evidence decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Provider / Transport","text","Provider / Transport · Standard Case"],["caseReference","Medical necessity evidence Reference","text","APD06-2026-001"],["paidAmount","Payer Paid Amount","currency",660500],["expectedAmount","Supported Transport Reimbursement","currency",779390],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Dispatch trip ingestion case","Patient payer eligibility case","Origin destination modifiers case","Loaded mileage calculation case","Service level determination case"]}),
feature("physician-certification-control","APD07","Physician certification control","Execute physician certification control using dispatches, trips, patient eligibility, origin and destination, loaded mileage, service level, medical necessity, certifications, signatures, claims, denials, and remittances.","Produce a governed physician certification control decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Provider / Transport","text","Provider / Transport · Standard Case"],["caseReference","Physician certification control Reference","text","APD07-2026-001"],["paidAmount","Payer Paid Amount","currency",660500],["expectedAmount","Supported Transport Reimbursement","currency",779390],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Dispatch trip ingestion case","Patient payer eligibility case","Origin destination modifiers case","Loaded mileage calculation case","Service level determination case"]}),
feature("repetitive-transport-authorization","APD08","Repetitive transport authorization","Execute repetitive transport authorization using dispatches, trips, patient eligibility, origin and destination, loaded mileage, service level, medical necessity, certifications, signatures, claims, denials, and remittances.","Produce a governed repetitive transport authorization decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Provider / Transport","text","Provider / Transport · Standard Case"],["caseReference","Repetitive transport authorization Reference","text","APD08-2026-001"],["paidAmount","Payer Paid Amount","currency",660500],["expectedAmount","Supported Transport Reimbursement","currency",779390],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Dispatch trip ingestion case","Patient payer eligibility case","Origin destination modifiers case","Loaded mileage calculation case","Service level determination case"]}),
feature("signature-evidence","APD09","Signature evidence","Execute signature evidence using dispatches, trips, patient eligibility, origin and destination, loaded mileage, service level, medical necessity, certifications, signatures, claims, denials, and remittances.","Produce a governed signature evidence decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Provider / Transport","text","Provider / Transport · Standard Case"],["caseReference","Signature evidence Reference","text","APD09-2026-001"],["paidAmount","Payer Paid Amount","currency",660500],["expectedAmount","Supported Transport Reimbursement","currency",779390],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Dispatch trip ingestion case","Patient payer eligibility case","Origin destination modifiers case","Loaded mileage calculation case","Service level determination case"]}),
feature("claim-generation","APD10","Claim generation","Execute claim generation using dispatches, trips, patient eligibility, origin and destination, loaded mileage, service level, medical necessity, certifications, signatures, claims, denials, and remittances.","Produce a governed claim generation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Provider / Transport","text","Provider / Transport · Standard Case"],["caseReference","Claim generation Reference","text","APD10-2026-001"],["paidAmount","Payer Paid Amount","currency",660500],["expectedAmount","Supported Transport Reimbursement","currency",779390],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Dispatch trip ingestion case","Patient payer eligibility case","Origin destination modifiers case","Loaded mileage calculation case","Service level determination case"]}),
feature("denial-classification","APD11","Denial classification","Execute denial classification using dispatches, trips, patient eligibility, origin and destination, loaded mileage, service level, medical necessity, certifications, signatures, claims, denials, and remittances.","Produce a governed denial classification decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Provider / Transport","text","Provider / Transport · Standard Case"],["caseReference","Denial classification Reference","text","APD11-2026-001"],["paidAmount","Payer Paid Amount","currency",660500],["expectedAmount","Supported Transport Reimbursement","currency",779390],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Dispatch trip ingestion case","Patient payer eligibility case","Origin destination modifiers case","Loaded mileage calculation case","Service level determination case"]}),
feature("appeal-package-generation","APD12","Appeal package generation","Execute appeal package generation using dispatches, trips, patient eligibility, origin and destination, loaded mileage, service level, medical necessity, certifications, signatures, claims, denials, and remittances.","Produce a governed appeal package generation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Provider / Transport","text","Provider / Transport · Standard Case"],["caseReference","Appeal package generation Reference","text","APD12-2026-001"],["paidAmount","Payer Paid Amount","currency",660500],["expectedAmount","Supported Transport Reimbursement","currency",779390],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Dispatch trip ingestion case","Patient payer eligibility case","Origin destination modifiers case","Loaded mileage calculation case","Service level determination case"]}),
feature("secondary-payer-coordination","APD13","Secondary payer coordination","Execute secondary payer coordination using dispatches, trips, patient eligibility, origin and destination, loaded mileage, service level, medical necessity, certifications, signatures, claims, denials, and remittances.","Produce a governed secondary payer coordination decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Provider / Transport","text","Provider / Transport · Standard Case"],["caseReference","Secondary payer coordination Reference","text","APD13-2026-001"],["paidAmount","Payer Paid Amount","currency",660500],["expectedAmount","Supported Transport Reimbursement","currency",779390],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Dispatch trip ingestion case","Patient payer eligibility case","Origin destination modifiers case","Loaded mileage calculation case","Service level determination case"]}),
feature("remittance-reconciliation","APD14","Remittance reconciliation","Execute remittance reconciliation using dispatches, trips, patient eligibility, origin and destination, loaded mileage, service level, medical necessity, certifications, signatures, claims, denials, and remittances.","Produce a governed remittance reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Provider / Transport","text","Provider / Transport · Standard Case"],["caseReference","Remittance reconciliation Reference","text","APD14-2026-001"],["paidAmount","Payer Paid Amount","currency",660500],["expectedAmount","Supported Transport Reimbursement","currency",779390],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Dispatch trip ingestion case","Patient payer eligibility case","Origin destination modifiers case","Loaded mileage calculation case","Service level determination case"]}),
feature("base-mileage-payer-analytics","APD15","Base mileage payer analytics","Execute base mileage payer analytics using dispatches, trips, patient eligibility, origin and destination, loaded mileage, service level, medical necessity, certifications, signatures, claims, denials, and remittances.","Produce a governed base mileage payer analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Provider / Transport","text","Provider / Transport · Standard Case"],["caseReference","Base mileage payer analytics Reference","text","APD15-2026-001"],["paidAmount","Payer Paid Amount","currency",660500],["expectedAmount","Supported Transport Reimbursement","currency",779390],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Dispatch trip ingestion case","Patient payer eligibility case","Origin destination modifiers case","Loaded mileage calculation case","Service level determination case"]})
]);
